### ISSUE TITLE
Sticker blocking

### ISSUE THREAD

**Issue by gdude2002** [spinfish/midnightcord#1]
I've just noticed that this theme includes [sticker-blocking CSS](https://github.com/spinfish/midnightcord/blob/1999ad3924db5716c6f96b874b474c60d7981466/theme.css#L173). I think the theme is fantastic overall, but that seems a little out of scope - it's more of a feature customization than an appearance once.

Would it be possible for you to move that to a separate theme, so that those of us that like stickers can view them without the blocking?

**Comment by spinfish** [comment]
I am so sorry for not responding to this. I plan to rewrite the theme and while doing so I will make sure to remove this!

**Comment by gdude2002** [comment]
No problem, thanks for working so hard on this!

**Comment by spinfish** [comment]
You're welcome! Fixed in a67b22c
